# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lenguaje de programacion')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
