# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltest',
            name='imagen',
        ),
        migrations.AddField(
            model_name='modeltest',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='modeltest',
            name='lastnametest',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
