# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modeltest',
            managers=[
                ('testQuery', django.db.models.manager.Manager()),
            ],
        ),
    ]
