# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171208_1732'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modeltest',
            managers=[
            ],
        ),
    ]
