# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171208_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
